# Generated by Django 4.2.10 on 2025-04-13 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('accuracy', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('weight', models.FloatField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('platelets', models.FloatField()),
                ('spo2', models.FloatField()),
                ('creatinine', models.FloatField()),
                ('hematocrit', models.FloatField()),
                ('aids', models.IntegerField()),
                ('lymphoma', models.IntegerField()),
                ('solid_tumor_with_metastasis', models.IntegerField()),
                ('heartrate', models.FloatField()),
                ('calcium', models.FloatField()),
                ('wbc', models.FloatField()),
                ('glucose', models.FloatField()),
                ('inr', models.FloatField()),
                ('potassium', models.FloatField()),
                ('sodium', models.FloatField()),
                ('ethnicity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.BooleanField(default=False)),
                ('confidence', models.FloatField()),
                ('is_correct', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='diabetes_predictor.patient')),
            ],
        ),
    ]
